import { useState } from 'react'
import { AlertCircle, CheckCircle, ArrowUp, ArrowDown, Filter, Shield, Heart, Info, Upload, X, HelpCircle, Printer, Share2, CreditCard, TrendingUp, TrendingDown, Minus, ChevronDown, ChevronUp } from 'lucide-react'
import type { BloodworkResult } from '../data/mockData'
import { BarChart, Bar, XAxis, YAxis, CartesianGrid, Tooltip, ResponsiveContainer, Cell, LineChart, Line } from 'recharts'
import LabImport from './LabImport'
import { medicalTermDefinitions } from './MedicalTermTooltip'
import RangeHistogram from './RangeHistogram'

// Anxiety-aware context messages for abnormal results
const getContextMessage = (result: BloodworkResult): { message: string; actionable: string; severity: 'low' | 'moderate' | 'attention' } => {
  const name = result.name.toLowerCase()

  if (result.status === 'high') {
    if (name.includes('glucose') || name.includes('hba1c')) {
      return {
        message: 'Slightly elevated but manageable with lifestyle changes',
        actionable: 'Diet modification and exercise typically show improvement in 2-3 months',
        severity: 'moderate'
      }
    }
    if (name.includes('ldl') || name.includes('cholesterol') || name.includes('triglyceride')) {
      return {
        message: 'Common finding - very responsive to treatment',
        actionable: 'Combination of medication and diet changes often normalizes within 6-8 weeks',
        severity: 'moderate'
      }
    }
  }

  if (result.status === 'low') {
    if (name.includes('vitamin d')) {
      return {
        message: 'Very common deficiency, especially in northern climates',
        actionable: 'Supplementation typically restores levels within 8-12 weeks',
        severity: 'low'
      }
    }
  }

  return {
    message: 'Your doctor will review and provide personalized guidance',
    actionable: 'Actionable recommendations will be provided after physician review',
    severity: 'attention'
  }
}

interface BloodworkViewProps {
  data: BloodworkResult[]
  testDate: string
}

export default function BloodworkView({ data, testDate }: BloodworkViewProps) {
  const [selectedCategory, setSelectedCategory] = useState<string>('All')
  const [showImportModal, setShowImportModal] = useState(false)
  const [showShareModal, setShowShareModal] = useState(false)
  const [showWalletCard, setShowWalletCard] = useState(false)
  const [expandedCards, setExpandedCards] = useState<Set<string>>(new Set())

  const toggleCardExpansion = (markerName: string) => {
    setExpandedCards(prev => {
      const newSet = new Set(prev)
      if (newSet.has(markerName)) {
        newSet.delete(markerName)
      } else {
        newSet.add(markerName)
      }
      return newSet
    })
  }

  const handlePrint = () => {
    window.print()
  }

  const handleShare = () => {
    setShowShareModal(true)
  }

  const handleWalletCard = () => {
    setShowWalletCard(true)
  }

  // Generate shareable summary text
  const generateSummary = () => {
    const abnormal = data.filter(r => r.status !== 'normal')
    const normal = data.length - abnormal.length
    return `Health Summary - ${new Date(testDate).toLocaleDateString()}

Total Tests: ${data.length}
Normal Results: ${normal}
Needs Attention: ${abnormal.length}

${abnormal.length > 0 ? `Areas to Monitor:
${abnormal.map(r => `• ${r.name}: ${r.value} ${r.unit} (${r.status})`).join('\n')}` : 'All results within normal range!'}

Generated by HealthSync AI`
  }

  const categories = ['All', ...Array.from(new Set(data.map(item => item.category)))]

  const filteredData = selectedCategory === 'All'
    ? data
    : data.filter(item => item.category === selectedCategory)

  const getStatusIcon = (status: string) => {
    if (status === 'normal') return <CheckCircle className="h-5 w-5 text-green-600" />
    if (status === 'low') return <ArrowDown className="h-5 w-5 text-orange-600" />
    if (status === 'high') return <ArrowUp className="h-5 w-5 text-red-600" />
    return null
  }

  const getStatusColor = (status: string) => {
    if (status === 'normal') return 'bg-green-50 border-green-200'
    if (status === 'low') return 'bg-orange-50 border-orange-200'
    if (status === 'high') return 'bg-red-50 border-red-200'
    return 'bg-gray-50 border-gray-200'
  }

  const getStatusTextColor = (status: string) => {
    if (status === 'normal') return 'text-green-900'
    if (status === 'low') return 'text-orange-900'
    if (status === 'high') return 'text-red-900'
    return 'text-gray-900'
  }

  const getBarColor = (status: string) => {
    if (status === 'normal') return '#10b981'
    if (status === 'low') return '#f97316'
    if (status === 'high') return '#ef4444'
    return '#6b7280'
  }

  const getTrendIcon = (trend: string) => {
    switch (trend) {
      case 'improving':
        return <TrendingUp className="h-4 w-4 text-green-600" />
      case 'worsening':
        return <TrendingDown className="h-4 w-4 text-red-600" />
      case 'stable':
        return <Minus className="h-4 w-4 text-gray-500" />
      default:
        return null
    }
  }

  // Parse reference range to get min/max for gauge
  const parseReferenceRange = (range: string): { min: number; max: number } | null => {
    // Handle ranges like "60-100", "<100", ">40", "3.5-5.5"
    if (range.includes('-')) {
      const parts = range.split('-').map(p => parseFloat(p.replace(/[^\d.]/g, '')))
      if (parts.length === 2 && !isNaN(parts[0]) && !isNaN(parts[1])) {
        return { min: parts[0], max: parts[1] }
      }
    } else if (range.startsWith('<')) {
      const max = parseFloat(range.replace(/[^\d.]/g, ''))
      if (!isNaN(max)) {
        return { min: 0, max: max * 1.5 } // Extend max for better visualization
      }
    } else if (range.startsWith('>')) {
      const min = parseFloat(range.replace(/[^\d.]/g, ''))
      if (!isNaN(min)) {
        return { min: min * 0.5, max: min * 2 } // Create range around minimum
      }
    }
    return null
  }

  const parseOptimalRange = (range: string): { min: number; max: number } | null => {
    if (range.includes('-')) {
      const parts = range.split('-').map(p => parseFloat(p.replace(/[^\d.]/g, '')))
      if (parts.length === 2 && !isNaN(parts[0]) && !isNaN(parts[1])) {
        return { min: parts[0], max: parts[1] }
      }
    } else if (range.startsWith('<')) {
      const max = parseFloat(range.replace(/[^\d.]/g, ''))
      if (!isNaN(max)) {
        return { min: 0, max }
      }
    }
    return null
  }

  // Prepare chart data for abnormal results
  const abnormalResults = data.filter(item => item.status !== 'normal')
  const chartData = abnormalResults.map(item => ({
    name: item.name.length > 20 ? item.name.substring(0, 20) + '...' : item.name,
    fullName: item.name,
    value: item.value,
    unit: item.unit,
    status: item.status,
  }))

  return (
    <div className="space-y-6">
      {/* Import Modal */}
      {showImportModal && (
        <div className="fixed inset-0 bg-black bg-opacity-50 flex items-center justify-center z-50 p-4">
          <div className="bg-white rounded-2xl shadow-2xl max-w-4xl w-full max-h-[90vh] overflow-y-auto">
            <div className="flex items-center justify-between p-4 border-b border-gray-200">
              <h2 className="text-xl font-bold text-gray-900">Import Lab Results</h2>
              <button
                onClick={() => setShowImportModal(false)}
                className="p-2 hover:bg-gray-100 rounded-lg transition-colors"
              >
                <X className="h-5 w-5 text-gray-500" />
              </button>
            </div>
            <div className="p-4">
              <LabImport />
            </div>
          </div>
        </div>
      )}

      {/* Share Modal */}
      {showShareModal && (
        <div className="fixed inset-0 bg-black bg-opacity-50 flex items-center justify-center z-50 p-4">
          <div className="bg-white rounded-2xl shadow-2xl max-w-lg w-full">
            <div className="flex items-center justify-between p-4 border-b border-gray-200">
              <h2 className="text-xl font-bold text-gray-900 flex items-center">
                <Share2 className="h-5 w-5 mr-2 text-purple-600" />
                Share with Family
              </h2>
              <button
                onClick={() => setShowShareModal(false)}
                className="p-2 hover:bg-gray-100 rounded-lg transition-colors"
              >
                <X className="h-5 w-5 text-gray-500" />
              </button>
            </div>
            <div className="p-6">
              <p className="text-sm text-gray-600 mb-4">
                Share a summary of your results with family members or caregivers.
              </p>
              <textarea
                readOnly
                value={generateSummary()}
                className="w-full h-48 p-3 border border-gray-300 rounded-lg text-sm font-mono bg-gray-50"
              />
              <div className="mt-4 flex space-x-3">
                <button
                  onClick={() => {
                    navigator.clipboard.writeText(generateSummary())
                    alert('Copied to clipboard!')
                  }}
                  className="flex-1 py-3 bg-purple-600 text-white rounded-lg font-semibold hover:bg-purple-700 transition-colors"
                >
                  Copy to Clipboard
                </button>
                <button
                  onClick={() => {
                    const subject = encodeURIComponent('My Health Results Summary')
                    const body = encodeURIComponent(generateSummary())
                    window.location.href = `mailto:?subject=${subject}&body=${body}`
                  }}
                  className="flex-1 py-3 bg-gray-100 text-gray-700 rounded-lg font-semibold hover:bg-gray-200 transition-colors"
                >
                  Send via Email
                </button>
              </div>
              <p className="text-xs text-gray-500 mt-3 text-center">
                This summary does not contain sensitive medical details.
              </p>
            </div>
          </div>
        </div>
      )}

      {/* Medication Wallet Card Modal */}
      {showWalletCard && (
        <div className="fixed inset-0 bg-black bg-opacity-50 flex items-center justify-center z-50 p-4">
          <div className="bg-white rounded-2xl shadow-2xl max-w-md w-full">
            <div className="flex items-center justify-between p-4 border-b border-gray-200">
              <h2 className="text-xl font-bold text-gray-900 flex items-center">
                <CreditCard className="h-5 w-5 mr-2 text-green-600" />
                Medication Wallet Card
              </h2>
              <button
                onClick={() => setShowWalletCard(false)}
                className="p-2 hover:bg-gray-100 rounded-lg transition-colors"
              >
                <X className="h-5 w-5 text-gray-500" />
              </button>
            </div>
            <div className="p-6">
              <p className="text-sm text-gray-600 mb-4">
                Print this card to keep in your wallet for emergency situations.
              </p>

              {/* Wallet Card Preview */}
              <div className="border-2 border-gray-300 rounded-xl p-4 bg-gradient-to-br from-blue-50 to-white">
                <div className="text-center border-b border-gray-200 pb-3 mb-3">
                  <h3 className="font-bold text-blue-900">MEDICAL INFORMATION</h3>
                  <p className="text-xs text-gray-600">HealthSync AI Patient Card</p>
                </div>

                <div className="space-y-2 text-sm">
                  <div>
                    <p className="text-xs text-gray-500 uppercase">Patient</p>
                    <p className="font-semibold">Robert Thompson</p>
                  </div>
                  <div>
                    <p className="text-xs text-gray-500 uppercase">Emergency Contact</p>
                    <p className="font-semibold">(512) 555-0199</p>
                  </div>
                  <div>
                    <p className="text-xs text-gray-500 uppercase">Key Health Notes</p>
                    <ul className="text-xs space-y-1">
                      <li>• Elevated cholesterol - on statin therapy</li>
                      <li>• Prediabetic - monitoring glucose</li>
                      <li>• Vitamin D deficiency</li>
                    </ul>
                  </div>
                  <div>
                    <p className="text-xs text-gray-500 uppercase">Physician</p>
                    <p className="font-semibold">Dr. Sarah Chen - (512) 555-0123</p>
                  </div>
                </div>

                <div className="mt-3 pt-3 border-t border-gray-200 text-center">
                  <p className="text-xs text-gray-500">Last Updated: {new Date().toLocaleDateString()}</p>
                </div>
              </div>

              <button
                onClick={() => window.print()}
                className="w-full mt-4 py-3 bg-green-600 text-white rounded-lg font-semibold hover:bg-green-700 transition-colors flex items-center justify-center"
              >
                <Printer className="h-4 w-4 mr-2" />
                Print Wallet Card
              </button>
              <p className="text-xs text-gray-500 mt-3 text-center">
                Cut along the border and fold to wallet size.
              </p>
            </div>
          </div>
        </div>
      )}

      {/* Header */}
      <div className="bg-white rounded-xl shadow-md p-6 border border-gray-100">
        <div className="flex items-center justify-between">
          <div>
            <h2 className="text-2xl font-bold text-gray-900">Blood Panel Results</h2>
            <p className="text-sm text-gray-600 mt-1">Test Date: {new Date(testDate).toLocaleDateString('en-US', {
              year: 'numeric',
              month: 'long',
              day: 'numeric'
            })}</p>
          </div>
          <div className="flex items-center space-x-2">
            <button
              onClick={handleShare}
              className="flex items-center space-x-2 px-3 py-2 bg-purple-100 text-purple-700 rounded-lg hover:bg-purple-200 transition-colors font-medium print:hidden"
              title="Share with Family"
            >
              <Share2 className="h-4 w-4" />
              <span className="hidden sm:inline">Share</span>
            </button>
            <button
              onClick={handleWalletCard}
              className="flex items-center space-x-2 px-3 py-2 bg-green-100 text-green-700 rounded-lg hover:bg-green-200 transition-colors font-medium print:hidden"
              title="Medication Wallet Card"
            >
              <CreditCard className="h-4 w-4" />
              <span className="hidden sm:inline">Wallet</span>
            </button>
            <button
              onClick={handlePrint}
              className="flex items-center space-x-2 px-3 py-2 bg-gray-100 text-gray-700 rounded-lg hover:bg-gray-200 transition-colors font-medium print:hidden"
              title="Print Results"
            >
              <Printer className="h-4 w-4" />
              <span className="hidden sm:inline">Print</span>
            </button>
            <button
              onClick={() => setShowImportModal(true)}
              className="flex items-center space-x-2 px-3 py-2 bg-blue-600 text-white rounded-lg hover:bg-blue-700 transition-colors font-medium print:hidden"
            >
              <Upload className="h-4 w-4" />
              <span className="hidden sm:inline">Import</span>
            </button>
            <div className="text-right ml-2">
              <p className="text-sm text-gray-600">Total Tests</p>
              <p className="text-3xl font-bold text-gray-900">{data.length}</p>
            </div>
          </div>
        </div>
      </div>

      {/* What Matters Most Right Now - Priority Section */}
      {abnormalResults.length > 0 && (
        <div className="bg-gradient-to-r from-orange-50 to-red-50 border-2 border-orange-300 rounded-xl p-6">
          <div className="flex items-start space-x-4 mb-5">
            <div className="bg-orange-500 p-3 rounded-full">
              <AlertCircle className="h-7 w-7 text-white" />
            </div>
            <div className="flex-1">
              <h2 className="text-2xl font-bold text-gray-900 mb-2">What Matters Most Right Now</h2>
              <p className="text-gray-700">
                These are your top priority markers based on clinical significance and improvement potential
              </p>
            </div>
          </div>

          <div className="space-y-4">
            {abnormalResults.slice(0, 5).map((marker, idx) => {
              const context = getContextMessage(marker)

              return (
                <div
                  key={marker.name}
                  className="bg-white rounded-lg p-5 border-l-4 border-orange-500 shadow-sm hover:shadow-md transition-shadow"
                >
                  <div className="flex items-start justify-between mb-3">
                    <div className="flex-1">
                      <div className="flex items-center space-x-3 mb-2">
                        <span className="text-2xl font-bold text-gray-400">#{idx + 1}</span>
                        <h3 className="text-lg font-bold text-gray-900">{marker.name}</h3>
                        <span className={`px-2 py-1 rounded-full text-xs font-bold uppercase ${
                          marker.status === 'high' ? 'bg-red-100 text-red-800' : 'bg-orange-100 text-orange-800'
                        }`}>
                          {marker.status}
                        </span>
                      </div>
                      <div className="flex items-baseline space-x-2 text-sm text-gray-600">
                        <span>Your value: <strong className="text-gray-900 text-base">{marker.value} {marker.unit}</strong></span>
                        <span>•</span>
                        <span>Target: {marker.optimalRange} {marker.unit}</span>
                      </div>
                    </div>
                    {getTrendIcon(marker.trend)}
                  </div>

                  <div className="bg-blue-50 rounded-lg p-3 mb-3">
                    <p className="text-sm text-blue-900 font-medium mb-1">{context.message}</p>
                    <p className="text-sm text-blue-800">{context.actionable}</p>
                  </div>

                  <button
                    onClick={() => toggleCardExpansion(marker.name)}
                    className="text-sm text-blue-600 hover:text-blue-800 font-semibold flex items-center"
                  >
                    View full details
                    {expandedCards.has(marker.name) ? <ChevronUp className="h-4 w-4 ml-1" /> : <ChevronDown className="h-4 w-4 ml-1" />}
                  </button>
                </div>
              )
            })}
          </div>

          {abnormalResults.length > 5 && (
            <p className="text-sm text-gray-600 mt-4 text-center">
              + {abnormalResults.length - 5} more markers to review below
            </p>
          )}
        </div>
      )}

      {/* Anxiety-Aware Context Message */}
      {abnormalResults.length > 0 && (
        <div className="bg-blue-50 border-2 border-blue-200 rounded-xl p-5">
          <div className="flex items-start space-x-4">
            <div className="bg-blue-100 p-3 rounded-full">
              <Shield className="h-6 w-6 text-blue-600" />
            </div>
            <div className="flex-1">
              <h3 className="font-bold text-blue-900 text-lg">Before You Worry...</h3>
              <p className="text-sm text-blue-800 mt-2">
                You have <span className="font-bold">{abnormalResults.length} result{abnormalResults.length !== 1 ? 's' : ''}</span> outside
                the normal range. Here's important context:
              </p>
              <ul className="mt-3 space-y-2 text-sm text-blue-900">
                <li className="flex items-center">
                  <CheckCircle className="h-4 w-4 mr-2 text-green-600" />
                  <span><strong>{data.length - abnormalResults.length} of {data.length}</strong> results are normal</span>
                </li>
                <li className="flex items-center">
                  <Heart className="h-4 w-4 mr-2 text-blue-600" />
                  <span>Minor abnormalities are <strong>common and easily corrected</strong></span>
                </li>
                <li className="flex items-center">
                  <Info className="h-4 w-4 mr-2 text-blue-600" />
                  <span>Your doctor will provide <strong>personalized treatment plans</strong></span>
                </li>
              </ul>
            </div>
          </div>
        </div>
      )}

      {/* Abnormal Results Chart */}
      {abnormalResults.length > 0 && (
        <div className="bg-white rounded-xl shadow-md p-6 border border-gray-100">
          <h3 className="text-lg font-bold text-gray-900 mb-4 flex items-center">
            <AlertCircle className="h-5 w-5 mr-2 text-yellow-600" />
            Abnormal Results Overview
          </h3>
          <ResponsiveContainer width="100%" height={300}>
            <BarChart data={chartData}>
              <CartesianGrid strokeDasharray="3 3" />
              <XAxis dataKey="name" angle={-45} textAnchor="end" height={100} fontSize={12} />
              <YAxis />
              <Tooltip
                content={({ active, payload }) => {
                  if (active && payload && payload.length) {
                    const data = payload[0].payload
                    return (
                      <div className="bg-white p-3 border border-gray-300 rounded-lg shadow-lg">
                        <p className="font-semibold">{data.fullName}</p>
                        <p className="text-sm">Value: {data.value} {data.unit}</p>
                        <p className="text-sm capitalize">Status: {data.status}</p>
                      </div>
                    )
                  }
                  return null
                }}
              />
              <Bar dataKey="value" radius={[8, 8, 0, 0]}>
                {chartData.map((entry, index) => (
                  <Cell key={`cell-${index}`} fill={getBarColor(entry.status)} />
                ))}
              </Bar>
            </BarChart>
          </ResponsiveContainer>
        </div>
      )}

      {/* Category Filter */}
      <div className="bg-white rounded-xl shadow-md p-4 border border-gray-100">
        <div className="flex items-center space-x-2">
          <Filter className="h-5 w-5 text-gray-600" />
          <span className="font-semibold text-gray-900">Filter by Category:</span>
          <div className="flex flex-wrap gap-2">
            {categories.map(category => (
              <button
                key={category}
                onClick={() => setSelectedCategory(category)}
                className={`px-4 py-2 rounded-lg font-medium transition-all ${
                  selectedCategory === category
                    ? 'bg-blue-600 text-white shadow-md'
                    : 'bg-gray-100 text-gray-700 hover:bg-gray-200'
                }`}
              >
                {category}
              </button>
            ))}
          </div>
        </div>
      </div>

      {/* Results Grid */}
      <div className="grid grid-cols-1 gap-4">
        {filteredData.map((result, index) => {
          const context = result.status !== 'normal' ? getContextMessage(result) : null
          const isExpanded = expandedCards.has(result.name)
          const referenceRange = parseReferenceRange(result.referenceRange)
          const optimalRange = result.optimalRange ? parseOptimalRange(result.optimalRange) : null
          const riskLevel = result.riskLevel || (result.status === 'normal' ? 'optimal' : result.status === 'low' ? 'borderline' : 'elevated')

          return (
            <div
              key={index}
              className={`${getStatusColor(result.status)} border-2 rounded-xl p-4 hover:shadow-lg transition-all`}
            >
              <div className="flex items-start justify-between mb-4">
                <div className="flex-1">
                  <div className="flex items-center space-x-2 mb-2">
                    {getStatusIcon(result.status)}
                    <h3 className={`font-bold text-lg ${getStatusTextColor(result.status)}`}>
                      {result.name}
                    </h3>
                    {medicalTermDefinitions[result.name] && (
                      <div className="group relative">
                        <HelpCircle className="h-4 w-4 text-blue-500 cursor-help" />
                        <div className="invisible group-hover:visible absolute z-50 bottom-full left-0 mb-2 w-72 p-3 bg-white border border-gray-300 rounded-lg shadow-xl">
                          <p className="font-semibold text-gray-900 text-sm mb-1">{result.name}</p>
                          <p className="text-sm text-gray-700 mb-2">{medicalTermDefinitions[result.name].short}</p>
                          <p className="text-xs text-gray-600">{medicalTermDefinitions[result.name].long}</p>
                        </div>
                      </div>
                    )}
                    {result.trend && (
                      <div className="flex items-center space-x-1 ml-2">
                        {getTrendIcon(result.trend)}
                        <span className={`text-xs font-medium ${
                          result.trend === 'improving' ? 'text-green-600' :
                          result.trend === 'worsening' ? 'text-red-600' :
                          'text-gray-500'
                        }`}>
                          {result.changePercent !== undefined && result.changePercent !== 0 && (
                            <>
                              {result.changePercent > 0 ? '+' : ''}{result.changePercent.toFixed(1)}%
                            </>
                          )}
                        </span>
                      </div>
                    )}
                  </div>
                  <p className="text-xs text-gray-600 mb-3">{result.category}</p>
                </div>
                <div className="flex items-center space-x-2">
                  <div className={`px-3 py-1 rounded-full text-xs font-bold uppercase ${
                    result.status === 'normal' ? 'bg-green-200 text-green-800' :
                    result.status === 'low' ? 'bg-orange-200 text-orange-800' :
                    'bg-red-200 text-red-800'
                  }`}>
                    {result.status}
                  </div>
                  {(result.historicalValues && result.historicalValues.length > 0) && (
                    <button
                      onClick={() => toggleCardExpansion(result.name)}
                      className="p-2 hover:bg-white/50 rounded-lg transition-colors"
                      title={isExpanded ? "Show less" : "Show more details"}
                    >
                      {isExpanded ? <ChevronUp className="h-4 w-4" /> : <ChevronDown className="h-4 w-4" />}
                    </button>
                  )}
                </div>
              </div>

              {/* Simplified Single Column Layout */}
              <div className="space-y-4">
                {/* Range Histogram Visualization */}
                {referenceRange && (
                  <div className="bg-white/50 rounded-lg p-4">
                    <RangeHistogram
                      value={result.value}
                      min={referenceRange.min}
                      max={referenceRange.max}
                      optimalMin={optimalRange?.min}
                      optimalMax={optimalRange?.max}
                      unit={result.unit}
                      riskLevel={riskLevel}
                    />
                  </div>
                )}

                {/* Top: Values Side by Side */}
                <div className="grid grid-cols-2 gap-3">
                  <div className="bg-white/50 rounded-lg p-3 text-center">
                    <p className="text-xs text-gray-600 uppercase font-medium mb-1">Your Result</p>
                    <p className={`text-3xl font-bold ${getStatusTextColor(result.status)}`}>
                      {result.value}
                    </p>
                    <p className="text-sm text-gray-500 mt-0.5">{result.unit}</p>
                  </div>
                  <div className="bg-white/50 rounded-lg p-3 text-center">
                    <p className="text-xs text-gray-600 uppercase font-medium mb-1">Reference</p>
                    <p className="text-xl font-semibold text-gray-700 mt-2">{result.referenceRange}</p>
                    <p className="text-sm text-gray-500 mt-0.5">{result.unit}</p>
                  </div>
                </div>

                {/* Risk Assessment - Full Width */}
                {result.riskLevel && (
                  <div className="bg-white/50 rounded-lg p-3 text-center">
                    <p className="text-xs text-gray-600 uppercase font-medium mb-1">Risk Level</p>
                    <p className={`text-2xl font-bold capitalize ${
                      riskLevel === 'optimal' ? 'text-green-700' :
                      riskLevel === 'borderline' ? 'text-yellow-700' :
                      riskLevel === 'elevated' ? 'text-orange-700' :
                      riskLevel === 'high' ? 'text-red-700' :
                      'text-red-900'
                    }`}>
                      {riskLevel}
                    </p>
                  </div>
                )}

                {/* Context Message for Abnormal Results */}
                {context && (
                  <div className={`p-3 rounded-lg ${
                    context.severity === 'low' ? 'bg-blue-50 border border-blue-200' :
                    context.severity === 'moderate' ? 'bg-yellow-50 border border-yellow-200' :
                    'bg-gray-50 border border-gray-200'
                  }`}>
                    <p className={`text-sm font-medium ${
                      context.severity === 'low' ? 'text-blue-800' :
                      context.severity === 'moderate' ? 'text-yellow-800' :
                      'text-gray-800'
                    }`}>
                      💡 {context.message}
                    </p>
                    <p className={`text-xs mt-1 ${
                      context.severity === 'low' ? 'text-blue-600' :
                      context.severity === 'moderate' ? 'text-yellow-700' :
                      'text-gray-600'
                    }`}>
                      {context.actionable}
                    </p>
                  </div>
                )}
              </div>

              {/* Expanded Section - Historical Trend */}
              {isExpanded && result.historicalValues && result.historicalValues.length > 0 && (
                <div className="mt-6 pt-4 border-t border-gray-200">
                  <h4 className="text-sm font-bold text-gray-900 mb-3">6-Month Trend</h4>
                  <ResponsiveContainer width="100%" height={200}>
                    <LineChart data={result.historicalValues}>
                      <CartesianGrid strokeDasharray="3 3" />
                      <XAxis
                        dataKey="date"
                        fontSize={10}
                        tickFormatter={(date) => new Date(date).toLocaleDateString('en-US', { month: 'short', day: 'numeric' })}
                      />
                      <YAxis fontSize={10} />
                      <Tooltip
                        content={({ active, payload }) => {
                          if (active && payload && payload.length) {
                            return (
                              <div className="bg-white p-2 border border-gray-300 rounded-lg shadow-lg">
                                <p className="text-xs font-semibold">{new Date(payload[0].payload.date).toLocaleDateString()}</p>
                                <p className="text-sm">{payload[0].value} {result.unit}</p>
                              </div>
                            )
                          }
                          return null
                        }}
                      />
                      <Line
                        type="monotone"
                        dataKey="value"
                        stroke={getBarColor(result.status)}
                        strokeWidth={2}
                        dot={{ fill: getBarColor(result.status), r: 4 }}
                      />
                    </LineChart>
                  </ResponsiveContainer>
                  <div className="mt-2 flex items-center justify-between text-xs text-gray-600">
                    <span>
                      Starting: {result.historicalValues[0].value} {result.unit}
                    </span>
                    <span>
                      Current: {result.value} {result.unit}
                    </span>
                    {result.trend && (
                      <span className={`font-medium ${
                        result.trend === 'improving' ? 'text-green-600' :
                        result.trend === 'worsening' ? 'text-red-600' :
                        'text-gray-500'
                      }`}>
                        {result.trend === 'improving' && '↗ Improving'}
                        {result.trend === 'worsening' && '↘ Worsening'}
                        {result.trend === 'stable' && '→ Stable'}
                      </span>
                    )}
                  </div>
                </div>
              )}
            </div>
          )
        })}
      </div>
    </div>
  )
}
